### ISSUE TITLE
Spacer

### ISSUE THREAD

**Issue by joebudi** [Budibase/bbui#81]
A component that adds space between other components. 

Original thinking:
Two variations; horizontal and vertical. 
Sizes; small, medium, large, possibly extra-small and extra-large

**Comment by kevmodrome** [comment]
What are some use-cases for this? I'm having trouble figuring out if this is needed when we have `--spacing-m` for example

**Comment by joebudi** [comment]
It makes it easier to build components such as the popover, where space is required between inputs and buttons. This can be done with the css, but having a spacer component means it can be done without having to add additional CSS.
