### ISSUE TITLE
Datalist component

### ISSUE THREAD

**Issue by joebudi** [Budibase/bbui#98]
We plan on removing {{context.Blah}} . The intentions are to remove this and replace with a dropdown with options. In some cases, the user might not want to use the dropdown, and might prefer to type a static value.

The html datalist component, with a few changes to match current design procedures (see select component (secondary)) will suffice. This component will be used a lot within the builder and should be small in size.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by mjashanks** [comment]
PR for this: #112
